# Generated by Django 5.2.8 on 2025-11-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=100, unique=True)),
                ('prev_policy_number', models.CharField(blank=True, max_length=100, null=True)),
                ('policy_type', models.CharField(choices=[('LIFE', 'Life Insurance'), ('HEALTH', 'Health Insurance'), ('AUTO', 'Vehicle Insurance'), ('HOME', 'Home Insurance')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('LAPSED', 'Lapsed'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending Renewal')], default='ACTIVE', max_length=20)),
                ('premium_amount', models.DecimalField(decimal_places=2, help_text='Annual Premium', max_digits=12)),
                ('sum_insured', models.DecimalField(decimal_places=2, max_digits=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('renewal_date', models.DateField(db_index=True, help_text='Date when renewal is due')),
                ('policy_file', models.FileField(blank=True, null=True, upload_to='policy_docs/')),
            ],
        ),
    ]
