# Generated by Django 5.2.8 on 2025-12-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='agency_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Commission Amount', max_digits=12),
        ),
        migrations.AddField(
            model_name='policy',
            name='od_net_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='OD Net Amount', max_digits=12),
        ),
        migrations.AddField(
            model_name='policy',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='s_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Surcharge Tax', max_digits=12),
        ),
        migrations.AddField(
            model_name='policy',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
