# Generated by Django 5.2.8 on 2025-11-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_date', models.DateField()),
                ('statement_file', models.FileField(upload_to='commission_statements/')),
                ('total_amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommissionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_expected', models.DecimalField(decimal_places=2, help_text='Calculated by System', max_digits=10)),
                ('amount_received', models.DecimalField(decimal_places=2, help_text='Extracted from Statement', max_digits=10)),
                ('status', models.CharField(choices=[('MATCHED', 'Fully Paid'), ('UNDERPAID', 'Underpaid (Discrepancy)'), ('OVERPAID', 'Overpaid'), ('MISSING', 'Missing from Statement')], default='MATCHED', max_length=20)),
                ('discrepancy_reason', models.TextField(blank=True, help_text='Auto-generated reason for mismatch')),
                ('transaction_date', models.DateField()),
            ],
        ),
    ]
