# Generated by Django 5.2.8 on 2025-11-25 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commissions', '0001_initial'),
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionstatement',
            name='carrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.carrier'),
        ),
        migrations.AddField(
            model_name='commissiontransaction',
            name='policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='policies.policy'),
        ),
        migrations.AddField(
            model_name='commissiontransaction',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='commissions.commissionstatement'),
        ),
    ]
